export default {
  SIGN_UP: 'SIGN_UP',
  PERSIST_LOGIN: 'PERSIST_LOGIN',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE_REQUEST: 'CREATE_REQUEST',
  RESET_CREATE_REQ_SUCC: 'RESET_CREATE_REQ_SUCC',
};
