export default {
  SIGN_UP: 'SIGN_UP',
  PERSIST_LOGIN: 'PERSIST_LOGIN',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  CREATE_REQUEST: 'CREATE_REQUEST',
  EDIT_REQUEST: 'EDIT_REQUEST',
  RESET_CREATE_REQ_SUCC: 'RESET_CREATE_REQ_SUCC',
  RESET_EDIT_REQ_SUCC: 'RESET_EDIT_REQ_SUCC',
  GET_USER_REQUESTS: 'GET_USER_REQUESTS',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  GET_REQUEST: 'GET_REQUEST',
  EDIT_INPUT_ON_CHANGE: 'EDIT_INPUT_ON_CHANGE',
};
